### PR TITLE
Fix populate arguments from DocumentedFeatures with non-arg constructors

### LINKED ISSUE #97: DocumentedFeatures do not populate arguments
After https://github.com/broadinstitute/barclay/commit/78b17117c264df3a39a1e29a3bf34f323b900eab, even if a documented feature has a non-arg constructor (such as `ReadFilter`), the arguments are not populated into the JSON nor in the property map. This is because they are not annotated with the `CommandLineProgramProperties`.

Maybe it should be enforced by Barclay to have every documented feature with a non-arg constructor, or have a marker for such a argument container.

### PR DESCRIPTION
**Pull request by magicDGS**
Closes #97

### CODE REVIEW

**Comment by magicDGS** [comment]
@cmnbroad - here its a simple bugfix that benefits from the mocking tests! Can you review? I've already in my code a couple of documented classes failing to populate the args without this fix...

File: src/main/java/org/broadinstitute/barclay/help/DefaultDocWorkUnitHandler.java [hunk 1]
```diff
@@ -191,19 +191,20 @@ public void processWorkUnit(
...
+            if (argumentContainer instanceof CommandLinePluginProvider) {
+                pluginDescriptors = ((CommandLinePluginProvider) argumentContainer).getPluginDescriptors();
+                clp = new CommandLineArgumentParser(
+                        argumentContainer, pluginDescriptors, Collections.emptySet()
+                );
+            } else {
+                clp = new CommandLineArgumentParser(argumentContainer);
+            }
+        } catch (IllegalAccessException | InstantiationException e) {
+            // only throw if the command line properties is set - CLP always require a non-arg constructor
```
Comment (cmnbroad) [inline src/main/java/org/broadinstitute/barclay/help/DefaultDocWorkUnitHandler.java]: Change this comment to say "DocumentedFeature does not assume a no-arg constructor unless it is also a CommandLineProgram".

File: src/test/java/org/broadinstitute/barclay/help/DefaultDocWorkUnitHandlerUnitTest.java [hunk 2]
```diff
@@ -80,6 +81,19 @@ public void testGetGroupSummaryForWorkUnit(final Class<?> docWorkUnitClazz, fina
...
+    private final class ClpWithoutNoArgsConstructor {
+        public ClpWithoutNoArgsConstructor(final int arg) { }
+    }
+
+    @Test(expectedExceptions = RuntimeException.class)
+    public void testProcessWorkUnitWithoutNoArgsConstructorClpThrows() {
+        final DefaultDocWorkUnitHandler handler = getDefaultWorkUnitHandlerInstance();
+        final DocWorkUnit workUnit = createMockWorkUnit(handler, ClpWithoutNoArgsConstructor.class, "", Collections.emptyMap());
+        handler.processWorkUnit(workUnit, Collections.emptyList(), Collections.emptyList());
+    }
```
Comment (cmnbroad) [inline src/test/java/org/broadinstitute/barclay/help/DefaultDocWorkUnitHandlerUnitTest.java]: Nice! We might as well add the converse as a unit test as well; a DocumentedFeature that doesn't have a no-arg constructor and doesn't have a CommandLineProgram annotation. Then just validate that the resulting workUnit property(s).

File: src/main/java/org/broadinstitute/barclay/help/DefaultDocWorkUnitHandler.java (hunk 1 above)
Comment (magicDGS) [reply src/main/java/org/broadinstitute/barclay/help/DefaultDocWorkUnitHandler.java]: Done.
(Because there is no concept of `CommandLineProgram` yet in Barclay, but only the annotation, I changed the ref to `CommandLineProgramProperties` instead)

File: src/test/java/org/broadinstitute/barclay/help/DefaultDocWorkUnitHandlerUnitTest.java (hunk 2 above)
Comment (magicDGS) [reply src/test/java/org/broadinstitute/barclay/help/DefaultDocWorkUnitHandlerUnitTest.java]: The current mocking framework is not able to process the work unit because it is not mocking the `ClassDoc.fields` and thus it throws a NPE, and even if it is mocking it, the codepaths for the `FieldDocs` will change in #105.

I think that testing the rest of the `processWorkUnit()` should be added in a different PR, because it requires much more work such as testing the different codepaths to populate different properties. I added a disabled test to show the issue...

**Comment by magicDGS** [comment]
Back to you @cmnbroad - there is still more work to do for a fully feature mock-testing framework to enable the kind of tests that you are asking for. Let me know what do you think!

File: src/test/java/org/broadinstitute/barclay/help/DefaultDocWorkUnitHandlerUnitTest.java (hunk 2 above)
Comment (cmnbroad) [reply src/test/java/org/broadinstitute/barclay/help/DefaultDocWorkUnitHandlerUnitTest.java]: Yeah, I see your point. I created https://github.com/broadinstitute/barclay/issues/107 for that. In the meantime lets not hold up these bug fix PRs since they're covered by integration tests.

**Comment by cmnbroad** [comment]
@magicDGS Yeah, lets remove them until we have a solution that allows them to work.

**Comment by cmnbroad** [comment]
Thanks for finding this one @magicDGS!
