### PR TITLE
Fix json name

### LINKED ISSUE #72: JSON output file names should not include the output file extension
For example, if the output extension is "html", the JSON files are currently called "workunit.html.json". This behavior was carried over from GATK3, but is unnecessary and a little misleading. The work unit output format and extension are independent of JSON, so the JSON file should just be called "workunit.json".

### PR DESCRIPTION
**Pull request by magicDGS**
Closes #72

### CODE REVIEW

File: src/main/java/org/broadinstitute/barclay/help/DocWorkUnitHandler.java [hunk 1]
```diff
@@ -56,6 +56,13 @@ public String getDestinationFilename(final DocWorkUnit workUnit) {
     }
 
     /**
+     * Returns the destination prefix (no paths) that the handler would like
```
Comment (cmnbroad) [inline src/main/java/org/broadinstitute/barclay/help/DocWorkUnitHandler.java]: I think this comment is wrong - its the JSON output file name not the destination prefix.

File: src/main/java/org/broadinstitute/barclay/help/DocWorkUnitHandler.java [hunk 2]
```diff
@@ -56,6 +56,13 @@ public String getDestinationFilename(final DocWorkUnit workUnit) {
...
+     */
+    public String getJsonFilename(final DocWorkUnit workUnit) {
```
Comment (cmnbroad) [inline src/main/java/org/broadinstitute/barclay/help/DocWorkUnitHandler.java]: Can you change the names of these new methods (this one and the DocWorkUnit one) so they use "JSON " instead of "Json" since its an acronym.

File: src/main/java/org/broadinstitute/barclay/help/DocWorkUnitHandler.java (hunk 1 above)
Comment (magicDGS) [inline src/main/java/org/broadinstitute/barclay/help/DocWorkUnitHandler.java]: True, I don't know what I was thinking about... Changed!

File: src/main/java/org/broadinstitute/barclay/help/DocWorkUnitHandler.java (hunk 2 above)
Comment (magicDGS) [inline src/main/java/org/broadinstitute/barclay/help/DocWorkUnitHandler.java]: Done.

**Comment by magicDGS** [comment]
I think that this is ready to go @cmnbroad once the tests pass! Thanks for reviewing!

**Comment by cmnbroad** [comment]
Thanks!

**Comment by magicDGS** [comment]
Thank you too for reviewing!
